import javax.swing.*;
import java.awt.*;

public class SecilenTelemetriBilgiPaneli extends JPanel {
    JLabel teamNoLabel;
    JLabel packageNoLabel;
    JLabel shipTimeLabel;
    JLabel pressureLabel;
    JLabel heightLabel;
    JLabel speedLabel;
    JLabel heatLabel;
    JLabel voltageLabel;
    JLabel gpsLatitudeLabel;
    JLabel gpsLongitudeLabel;
    JLabel gpsAltitudeLabel;
    JLabel pitchLabel;
    JLabel rollLabel;
    JLabel yawLabel;
    JLabel statueLabel;
    JLabel turnsNoLabel;
    JLabel videoTransmissionLabel;
    JTextField teamNoTextF;
    JTextField packageNoTextF;
    JTextField shipTimeTextF;
    JTextField pressureTextF;
    JTextField heightTextF;
    JTextField speedTextF;
    JTextField heatTextF;
    JTextField voltageTextF;
    JTextField gpsLatitudeTextF;
    JTextField gpsLongitudeTextF;
    JTextField gpsAltitudeTextF;
    JTextField pitchTextF;
    JTextField rollTextF;
    JTextField yawTextF;
    JTextField statueTextF;
    JTextField turnsNoTextF;
    JTextField videoTransmissionTextF;
    public SecilenTelemetriBilgiPaneli(){
        setLayout(null);

        JLabel seciliVeriAlani = new JLabel("Seçili Veri Alanı");
        teamNoLabel = new JLabel("Takım Numarası:");
        teamNoTextF = new JTextField();
        packageNoLabel = new JLabel("Paket Numarası:");
        packageNoTextF = new JTextField();
        shipTimeLabel = new JLabel("Gönderim Zamanı:");
        shipTimeTextF = new JTextField();
        pressureLabel = new JLabel("Basınç:");
        pressureTextF = new JTextField();
        heightLabel = new JLabel("Yükseklik:");
        heightTextF = new JTextField();
        speedLabel = new JLabel("İniş Hızı:");
        speedTextF = new JTextField();
        heatLabel = new JLabel("Sıcaklık:");
        heatTextF = new JTextField();
        voltageLabel = new JLabel("Pil Gerilimi:");
        voltageTextF = new JTextField();
        gpsLatitudeLabel = new JLabel("GPS Latitude:");
        gpsLatitudeTextF = new JTextField();
        gpsLongitudeLabel = new JLabel("GPS Longitude:");
        gpsLongitudeTextF = new JTextField();
        gpsAltitudeLabel = new JLabel("GPS Altitude:");
        gpsAltitudeTextF = new JTextField();
        pitchLabel = new JLabel("Pitch:");
        pitchTextF = new JTextField();
        rollLabel = new JLabel("Roll:");
        rollTextF = new JTextField();
        yawLabel = new JLabel("Yaw:");
        yawTextF = new JTextField();
        statueLabel = new JLabel("Uydu Statüsü:");
        statueTextF = new JTextField();
        turnsNoLabel = new JLabel("Dönüş Sayısı:");
        turnsNoTextF = new JTextField();
        videoTransmissionLabel = new JLabel("Video Aktarım:");
        videoTransmissionTextF = new JTextField();

        seciliVeriAlani.setFont(new java.awt.Font("Tahoma", Font.BOLD,14));
        seciliVeriAlani.setBounds(3,3,120,25);
        teamNoLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        teamNoLabel.setBounds(3,50,80,25);
        teamNoTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        teamNoTextF.setBounds(93,50,127,25);
        packageNoLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        packageNoLabel.setBounds(3,110,80,25);
        packageNoTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        packageNoTextF.setBounds(93,110,127,25);
        shipTimeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        shipTimeLabel.setBounds(3,165,90,25);
        shipTimeTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        shipTimeTextF.setBounds(93,165,127,25);
        pressureLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        pressureLabel.setBounds(230,5,35,25);
        pressureTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        pressureTextF.setBounds(280,5,70,25);
        heightLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        heightLabel.setBounds(230,50,47,25);
        heightTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        heightTextF.setBounds(285,50,70,25);
        speedLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        speedLabel.setBounds(230,110,47,25);
        speedTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        speedTextF.setBounds(285,110,70,25);
        heatLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        heatLabel.setBounds(230,165,47,25);
        heatTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        heatTextF.setBounds(285,165,70,25);
        voltageLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        voltageLabel.setBounds(375,5,75,25);
        voltageTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        voltageTextF.setBounds(460,5,100,25);
        gpsLatitudeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsLatitudeLabel.setBounds(375,50,75,25);
        gpsLatitudeTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsLatitudeTextF.setBounds(460,50,100,25);
        gpsLongitudeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsLongitudeLabel.setBounds(375,110,75,25);
        gpsLongitudeTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsLongitudeTextF.setBounds(460,110,100,25);
        gpsAltitudeLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsAltitudeLabel.setBounds(375,165,75,25);
        gpsAltitudeTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        gpsAltitudeTextF.setBounds(460,165,100,25);
        pitchLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        pitchLabel.setBounds(615,5,30,25);
        pitchTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        pitchTextF.setBounds(655,5,145,25);
        rollLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        rollLabel.setBounds(615,50,25,25);
        rollTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        rollTextF.setBounds(655,50,145,25);
        yawLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        yawLabel.setBounds(615,110,25,25);
        yawTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        yawTextF.setBounds(655,110,145,25);
        statueLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        statueLabel.setBounds(575,165,70,25);
        statueTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        statueTextF.setBounds(655,165,145,25);
        turnsNoLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        turnsNoLabel.setBounds(815,5,70,25);
        turnsNoTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        turnsNoTextF.setBounds(890,5,100,25);
        videoTransmissionLabel.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        videoTransmissionLabel.setBounds(815,50,70,25);
        videoTransmissionTextF.setFont(new java.awt.Font("Tahoma", Font.PLAIN,11));
        videoTransmissionTextF.setBounds(890,50,100,25);

        add(seciliVeriAlani);
        add(teamNoLabel);
        add(teamNoTextF);
        add(packageNoLabel);
        add(packageNoTextF);
        add(shipTimeLabel);
        add(shipTimeTextF);
        add(pressureLabel);
        add(pressureTextF);
        add(heightLabel);
        add(heightTextF);
        add(speedLabel);
        add(speedTextF);
        add(heatLabel);
        add(heatTextF);
        add(voltageLabel);
        add(voltageTextF);
        add(gpsLatitudeLabel);
        add(gpsLatitudeTextF);
        add(gpsLongitudeLabel);
        add(gpsLongitudeTextF);
        add(gpsAltitudeLabel);
        add(gpsAltitudeTextF);
        add(pitchLabel);
        add(pitchTextF);
        add(rollLabel);
        add(rollTextF);
        add(yawLabel);
        add(yawTextF);
        add(statueLabel);
        add(statueTextF);
        add(turnsNoLabel);
        add(turnsNoTextF);
        add(videoTransmissionLabel);
        add(videoTransmissionTextF);
    }
}
